name: my_website
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_svg: ^2.0.10+1
  get_it: ^7.2.0
  go_router: ^14.0.1
  path_provider: ^2.0.11
  shared_preferences: ^2.0.15

dev_dependencies:
  build_runner: ^2.2.0

  flutter_gen_runner: ^5.7.0

  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/svgs/

  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/poppins/Poppins-Regular.ttf
        - asset: fonts/poppins/Poppins-Light.ttf
        - asset: fonts/poppins/Poppins-Bold.ttf
          weight: 800
        - asset: fonts/poppins/Poppins-SemiBold.ttf
          weight: 500

    - family: Euclid
      fonts:
        - asset: fonts/euclid/Euclid-Regular.ttf
flutter_gen:
  output: lib/constants
  integrations: null
  flutter_svg: true
