name: my_website
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter_web_plugins:
    sdk: flutter
  bloc: ^8.1.4
  collection: ^1.18.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.4
  get_it: ^7.2.0
  go_router: ^14.2.7
  json_annotation: ^4.9.0
  markdown_widget: ^2.3.2+6
  path_provider: ^2.0.11
  shared_preferences: ^2.0.15
  url_launcher: ^6.3.0

dev_dependencies:
  build_runner: ^2.4.12

  flutter_gen_runner: ^5.7.0

  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter:
  assets: 
    - assets/svgs/
    - assets/blogs/

  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/poppins/Poppins-Regular.ttf
        - asset: fonts/poppins/Poppins-Light.ttf
        - asset: fonts/poppins/Poppins-Bold.ttf
          weight: 800
        - asset: fonts/poppins/Poppins-SemiBold.ttf
          weight: 500

    - family: Euclid
      fonts:
        - asset: fonts/euclid/Euclid-Regular.ttf
flutter_gen:
  output: lib/constants
  integrations: null
  flutter_svg: true
