// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAqy-kGWvLHj4QvyGb14tntn-pEDfOlp8',
    appId: '1:964613434103:android:13439fbc24b5a0c89741f2',
    messagingSenderId: '964613434103',
    projectId: 'aashisregmi-com-np',
    storageBucket: 'aashisregmi-com-np.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDePB6gtwGr-vuVWd1Ra8gwlFUlOmRwcj0',
    appId: '1:964613434103:ios:27b620f624c7ce929741f2',
    messagingSenderId: '964613434103',
    projectId: 'aashisregmi-com-np',
    storageBucket: 'aashisregmi-com-np.appspot.com',
    iosBundleId: 'com.example.myWebsite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDePB6gtwGr-vuVWd1Ra8gwlFUlOmRwcj0',
    appId: '1:964613434103:ios:27b620f624c7ce929741f2',
    messagingSenderId: '964613434103',
    projectId: 'aashisregmi-com-np',
    storageBucket: 'aashisregmi-com-np.appspot.com',
    iosBundleId: 'com.example.myWebsite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZg8Gnp1EI6mJ1fuMk7wq9ZEPNR4jV-pQ',
    appId: '1:964613434103:web:3222e0718d81ed059741f2',
    messagingSenderId: '964613434103',
    projectId: 'aashisregmi-com-np',
    authDomain: 'aashisregmi-com-np.firebaseapp.com',
    storageBucket: 'aashisregmi-com-np.appspot.com',
    measurementId: 'G-PW4L3NGV62',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZg8Gnp1EI6mJ1fuMk7wq9ZEPNR4jV-pQ',
    appId: '1:964613434103:web:3ab8ddc3e22346699741f2',
    messagingSenderId: '964613434103',
    projectId: 'aashisregmi-com-np',
    authDomain: 'aashisregmi-com-np.firebaseapp.com',
    storageBucket: 'aashisregmi-com-np.appspot.com',
    measurementId: 'G-0M7BGL9RQ8',
  );

}